---

- name: ping test
  connection: network_cli
  gather_facts: false
  hosts: ansible4

  tasks:

  - name: Test reachability to 8.8.8.8 using mgmt vrf
    nxos_ping:
      dest: 8.8.8.8
      vrf: management
      username: admin
      password: password

...
